"""Default configuration values for FrameFlow."""

DEFAULT_ENVIRONMENT = "development"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000

DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_DATABASE_PATH = "data/frameflow.db"
DEFAULT_PHOTO_LIBRARY = "photos"

DEFAULT_SYNC_ENABLED = False
DEFAULT_SYNC_INTERVAL_SECONDS = 300
